Licence -> License
Lombiq/UI-Testing-Toolbox pull request #137
Opened 2022-02-25 07:16 UTC by hishamco

2022-02-25 23:16 UTC, Piedone requested changes

2022-02-25 23:16 UTC, Piedone commented on Lombiq.Tests.UI.AppExtensions/Lombiq.Tests.UI.AppExtensions.csproj
> +    <PackageLicenseFile>License.md</PackageLicenseFile>
All of these files need to be renamed.

2022-02-26 06:54 UTC, hishamco commented on Lombiq.Tests.UI.AppExtensions/Lombiq.Tests.UI.AppExtensions.csproj
> +    <PackageLicenseFile>License.md</PackageLicenseFile>
Seems I miss to push them accidentally in the Git ;(

2022-02-26 15:32 UTC, merged

2022-02-26 15:32 UTC, Piedone commented
Thanks!