OSOE-46: Use WebApplicationFactory directly instead of running the tested app with the dotnet CLI
Lombiq/UI-Testing-Toolbox pull request #186
Opened 2022-07-20 05:45 UTC by dministro

Fixes GH-101
OSOE-46

2022-09-27 21:56 UTC, Piedone commented
Great migration docs, BTW!

2022-09-28 00:16 UTC, DAud-IcI requested changes

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +2. Remove `Lombiq.Tests.UI.AppExtensions` project reference or NuGet package from the web app under test.
```suggestion
1. Prepare the web app to be tested as described in [Basic tests with the default WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?source=recommendations&view=aspnetcore-6.0#basic-tests-with-the-default-webapplicationfactory).
2. Remove `Lombiq.Tests.UI.AppExtensions` project reference or NuGet package from the web app.
```

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> ++ // As described here(https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0).
```suggestion
+ // As described here (https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-6.0).
```

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +1. Add the web app project under test as a `Project reference` to UI test project.
Only use backticks for code.

```suggestion
1. Add a _project reference_ of the web app to be tested to the UI test project.
```

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +There is a breaking change in adding command line arguments to the WebApplication.
It's not so great that people have to have read this document to know about this. Please add a stub `Add(string)` method to `InstanceCommandLineArgumentsBuilder` that's marked `[Obsolete]` and throws `NotSupportedException when called`.

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +The following extension methods result in the same and no breaking change in the signatures, but they behave a bit differently. Using `WebApplicationFactory` opened the possibility to use OC services
```suggestion
The following extension methods behave largely the same and their signatures didn't change. Using `WebApplicationFactory` made it possible to use OC services directly instead of using _controller actions_ invoked via browser navigation.
```

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +This means that calling the extension methods below no longer results in browser navigation.
```suggestion
This means that calling the extension methods below don't cause browser navigation any more.
```

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +_Here is a sample for better understanding_:
Why is this italicized?

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/Migration.md
> +The original code with the new behavior resulted in a failing test, because the browser pointed to the `Home page` before `await context.EnablePrivacyConsentBannerFeatureAsync()(=> context.EnableFeat
```suggestion
The original code with the new behavior failed a test, because the browser pointed to the _Home page_ before `await context.EnablePrivacyConsentBannerFeatureAsync()(=> context.EnableFeatureDirectlyAsync({featureId})`. So the `context.EnableFeatureDirectlyAsync` doesn't navigate away, the `await context.GoToHomePageAsync()` call does nothing, and the consent banner doesn't come up.
```

2022-09-28 00:16 UTC, sarahelsaig commented on Lombiq.Tests.UI/Docs/TestableOrchardCoreApps.md
> +  1. Prepare the web app uneder test as described in [Basic tests with the default WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?source=recommendations&vi
```suggestion
  1. Prepare the web app to be testes as described in [Basic tests with the default WebApplicationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?source=recommendations&view=aspnetcore-6.0#basic-tests-with-the-default-webapplicationfactory).
```

2022-09-28 00:16 UTC, DAud-IcI commented on Lombiq.Tests.UI/Extensions/VisualVerificationUITestContextExtensions.cs
> +        }
What is this?

2022-09-28 00:16 UTC, DAud-IcI commented on Lombiq.Tests.UI/Models/InstanceCommandLineArgs.cs
> +        _arguments.Add($"{PrepareArg(key)}={value}");
Wrap the string interpolation with `FormattableString.Invariant()` because value may be an `IFormattable` such as `int`.

2022-09-28 00:16 UTC, DAud-IcI commented on Lombiq.Tests.UI/Models/InstanceCommandLineArgs.cs
> +        if (!argument.StartsWith("--", System.StringComparison.InvariantCultureIgnoreCase))
This handles `--argument`, but not `-argument` which is also valid. So just doing `.TrimStart('-')` would be better.

2022-09-28 00:16 UTC, DAud-IcI commented on Lombiq.Tests.UI/Services/OrchardCoreHosting/OrchardApplicationFactory.cs
> +                    "Pease add ConfigurationManager instance to WebApplicationBuilder.Services in your Program.cs!");
Use `nameof`.

2022-09-29 16:07 UTC, dministro commented on Lombiq.Tests.UI/Extensions/VisualVerificationUITestContextExtensions.cs
> +        }
Commented in code

2022-10-14 07:54 UTC, DAud-IcI commented on Lombiq.Tests.UI/Models/InstanceCommandLineArgs.cs
> +        => $"--{argument.TrimStart('-')}";
```suggestion
    private static string PrepareArg(string argument) =>
        $"--{argument.TrimStart('-')}";
```

2022-10-14 07:55 UTC, DAud-IcI commented on Lombiq.Tests.UI/Services/OrchardCoreHosting/OrchardApplicationFactory.cs
> +                    $"Pease add {nameof(ConfigurationManager)} instance to WebApplicationBuilder.Services in your Program.cs!");
```suggestion
        var builder = services
                .LastOrDefault(descriptor => descriptor.ServiceType == typeof(OrchardCoreBuilder))?
                .ImplementationInstance as OrchardCoreBuilder
                ?? throw new InvalidOperationException(
                    "Please call WebApplicationBuilder.Services.AddOrchardCms() in your Program.cs!");
        var configuration = services
                .LastOrDefault(descriptor => descriptor.ServiceType == typeof(ConfigurationManager))?
                .ImplementationInstance as ConfigurationManager
                ?? throw new InvalidOperationException(
                    $"Please add {nameof(ConfigurationManager)} instance to WebApplicationBuilder.Services in your Program.cs!");
```

2022-10-14 08:36 UTC, merged