WALMA-99: Flaky UI tests
Lombiq/UI-Testing-Toolbox pull request #251
Opened 2023-01-10 14:02 UTC by DemeSzabolcs

WALMA-99

2023-01-16 18:00 UTC, dministro commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +    private static readonly SemaphoreSlim _semaphore;
```suggestion
    private static readonly SemaphoreSlim _semaphore = new(1, 1);
```

2023-01-16 18:00 UTC, dministro commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +        _semaphore = new(1, 1);
```suggestion
```

2023-01-18 14:34 UTC, dministro requested changes

2023-01-18 14:34 UTC, dministro commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +                    result = await DockerExecuteAndGetOutputAsync(
In the case of `InvalidOperationException` thrown by `DockerExecuteAndGetOutputAsync` the retry logic does not apply.

Can we create a new method for this check? With a new method we can avoid the `S134` warning.
E.g.: `EnsureDockerFileExists`

2023-01-18 14:34 UTC, dministro commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +                        remote[..remote.LastIndexOf('/')]);
```suggestion
                        Path.GetFileName(remote);
```

2023-01-18 14:34 UTC, dministro commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +                    throw new FileNotFoundException(
Please create a custom exception for this. `FileNotFoundException` doesn't fit the real meaning of the context.
E.g.: `DockerFileCopyExcption` or similar.

2023-01-18 16:45 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +                        remote[..remote.LastIndexOf('/')]);
I think this is wrong. It's on the docker so we can't use `Path.GetFileName(remote)`. UI test also fails with this.

2023-01-18 18:06 UTC, dministro commented on Lombiq.Tests.UI/Services/SqlServerManager.cs
> +                        remote[..remote.LastIndexOf('/')]);
Yes, you are right. The directory is needed here and not the file name. Sorry.
Please use `Path.GetDirectoryName(remote)` instead.

2023-01-19 07:35 UTC, dministro approved these changes

2023-01-19 07:35 UTC, merged