LMBQ-113: During element screenshot, add 1px tolerance
Lombiq/UI-Testing-Toolbox pull request #269
Opened 2023-04-15 11:38 UTC by 0liver

2023-04-16 22:03 UTC, DemeSzabolcs requested changes

2023-04-16 22:03 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Extensions/ScreenshotUITestContextExtensions.cs
> +            // here. In that case, we keep the elementSize as is, but reduce the Location coordinate by 1 so that cropping
Long line. 120+

2023-04-16 22:03 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Extensions/ScreenshotUITestContextExtensions.cs
> +        return screenshot.Clone(ctx => ctx.Crop(cropRectangle));
I think changing `ctx` to something more descriptive would be good too.

2023-04-16 22:03 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Extensions/ScreenshotUITestContextExtensions.cs
> +        $"{size.Width.ToTechnicalString()} x {size.Height.ToTechnicalString()}";
Both of these functions are only used in one place.

2023-04-16 22:03 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Services/OrchardCoreUITestExecutorConfiguration.cs
> +            // HTML imports are somehow used by Selenium or something but this deprecation notice is always there for every
Long comment. 120+ characters.

2023-04-17 09:22 UTC, 0liver commented on Lombiq.Tests.UI/Extensions/ScreenshotUITestContextExtensions.cs
> +        $"{size.Width.ToTechnicalString()} x {size.Height.ToTechnicalString()}";
That is correct. They help keep the error message string in line 133 readable. I think this adds enough value to justify their existence.

2023-04-19 13:32 UTC, DemeSzabolcs approved these changes

2023-04-19 14:22 UTC, merged