Adding the ability to do UI testing on a remote environment
Lombiq/UI-Testing-Toolbox pull request #341
Opened 2024-02-08 00:13 UTC by Piedone

2024-02-08 21:26 UTC, dministro requested changes

2024-02-08 21:26 UTC, dministro commented on Lombiq.Tests.UI/UITestBase.cs
I would make this more generic:
```diff
 Lombiq.Tests.UI/OrchardCoreUITestBase.cs                       | 10 +++++++---
 Lombiq.Tests.UI/RemoteUITestBase.cs                            |  8 +++++++-
 .../Services/OrchardCoreUITestExecutorConfiguration.cs         |  9 ++++++++-
 Lombiq.Tests.UI/UITestBase.cs                                  |  8 ++++----
 Lombiq.Tests.UI/pnpm-lock.yaml                                 |  2 +-
 5 files changed, 27 insertions(+), 10 deletions(-)

diff --git a/Lombiq.Tests.UI/OrchardCoreUITestBase.cs b/Lombiq.Tests.UI/OrchardCoreUITestBase.cs
index 778ad674..383c4e23 100644
--- a/Lombiq.Tests.UI/OrchardCoreUITestBase.cs
+++ b/Lombiq.Tests.UI/OrchardCoreUITestBase.cs
@@ -333,9 +333,13 @@ public abstract class OrchardCoreUITestBase<TEntryPoint> : UITestBase
 
         if (changeConfigurationAsync != null) await changeConfigurationAsync(configuration);
 
-        await ExecuteOrchardCoreTestAsync(
-            (configuration, contextId) =>
-                new OrchardCoreInstance<TEntryPoint>(configuration.OrchardCoreConfiguration, contextId, configuration.TestOutputHelper),
+        await ExecuteUITestAsync(
+            () => UITestExecutor.ExecuteOrchardCoreTestAsync(
+                (configuration, contextId) =>
+                    new OrchardCoreInstance<TEntryPoint>(
+                        configuration.OrchardCoreConfiguration, contextId, configuration.TestOutputHelper),
+                testManifest,
+                configuration),
             testManifest,
             configuration);
     }
diff --git a/Lombiq.Tests.UI/RemoteUITestBase.cs b/Lombiq.Tests.UI/RemoteUITestBase.cs
index e4984f0d..a586d207 100644
--- a/Lombiq.Tests.UI/RemoteUITestBase.cs
+++ b/Lombiq.Tests.UI/RemoteUITestBase.cs
@@ -71,6 +71,12 @@ public abstract class RemoteUITestBase : UITestBase
 
         if (changeConfigurationAsync != null) await changeConfigurationAsync(configuration);
 
-        await ExecuteOrchardCoreTestAsync((_, _) => new RemoteInstance(baseUri), testManifest, configuration);
+        await ExecuteUITestAsync(
+            () => UITestExecutor.ExecuteOrchardCoreTestAsync(
+                (_, _) => new RemoteInstance(baseUri),
+                testManifest,
+                configuration),
+            testManifest,
+            configuration);
     }
 }
diff --git a/Lombiq.Tests.UI/Services/OrchardCoreUITestExecutorConfiguration.cs b/Lombiq.Tests.UI/Services/OrchardCoreUITestExecutorConfiguration.cs
index 29d5ae5f..d8e3d324 100644
--- a/Lombiq.Tests.UI/Services/OrchardCoreUITestExecutorConfiguration.cs
+++ b/Lombiq.Tests.UI/Services/OrchardCoreUITestExecutorConfiguration.cs
@@ -22,7 +22,14 @@ public enum Browser
     InternetExplorer,
 }
 
-public class OrchardCoreUITestExecutorConfiguration
+public interface IGithubActionsConfiguration
+{
+    bool ExtendGitHubActionsOutput { get; }
+    GitHubActionsOutputConfiguration GitHubActionsOutputConfiguration { get; }
+    ITestOutputHelper TestOutputHelper { get; set; }
+}
+
+public class OrchardCoreUITestExecutorConfiguration : IGithubActionsConfiguration
 {
     public static readonly Func<IWebApplicationInstance, Task> AssertAppLogsAreEmptyAsync = app =>
         app.LogsShouldBeEmptyAsync();
diff --git a/Lombiq.Tests.UI/UITestBase.cs b/Lombiq.Tests.UI/UITestBase.cs
index 9b15a64c..a7487bb4 100644
--- a/Lombiq.Tests.UI/UITestBase.cs
+++ b/Lombiq.Tests.UI/UITestBase.cs
@@ -15,10 +15,10 @@ public abstract class UITestBase
 
     protected UITestBase(ITestOutputHelper testOutputHelper) => _testOutputHelper = testOutputHelper;
 
-    protected async Task ExecuteOrchardCoreTestAsync(
-        WebApplicationInstanceFactory webApplicationInstanceFactory,
+    protected async Task ExecuteUITestAsync(
+        Func<Task> executor,
         UITestManifest testManifest,
-        OrchardCoreUITestExecutorConfiguration configuration)
+        IGithubActionsConfiguration configuration)
     {
         var originalTestOutputHelper = _testOutputHelper;
         Action afterTest = null;
@@ -33,7 +33,7 @@ public abstract class UITestBase
 
         try
         {
-            await UITestExecutor.ExecuteOrchardCoreTestAsync(webApplicationInstanceFactory, testManifest, configuration);
+            await executor.Invoke();
         }
         finally
         {
diff --git a/Lombiq.Tests.UI/pnpm-lock.yaml b/Lombiq.Tests.UI/pnpm-lock.yaml
index d334190a..cd6c0973 100644
--- a/Lombiq.Tests.UI/pnpm-lock.yaml
+++ b/Lombiq.Tests.UI/pnpm-lock.yaml
@@ -1,7 +1,7 @@
 lockfileVersion: '6.0'
 
 settings:
-  autoInstallPeers: true
+  autoInstallPeers: false
   excludeLinksFromLockfile: false
 
 dependencies:
```

2024-02-08 22:10 UTC, Piedone commented on Lombiq.Tests.UI/UITestBase.cs
This is a patch file, right? Because it fails with:

> Applying: Lombiq.Tests.UI/OrchardCoreUITestBase.cs
    | 10 +++++++---
error: corrupt patch at line 99
error: could not build fake ancestor
hint: Use 'git am --show-current-patch=diff' to see the failed patch Patch failed at 0001 Lombiq.Tests.UI/OrchardCoreUITestBase.cs
               | 10 +++++++---
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

2024-02-08 22:13 UTC, Piedone commented on Lombiq.Tests.UI/UITestBase.cs
Or just commit it, please (just this repo is enough) so I don't have to recreate by hand. (And we can revert if necessary.)

2024-02-09 02:22 UTC, Piedone commented on Lombiq.Tests.UI/UITestBase.cs
I'd go with [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) here. If we take away what starts with `UITestExecutor.ExecuteOrchardCoreTestAsync()`, including creating the `context` (which provides a lot of useful stuff) then not much remains. At that point, you can just write your tests completely from scratch.

2024-02-09 20:50 UTC, dministro approved these changes

2024-02-09 21:01 UTC, merged