OSOE-770: Add support for structured html-validate output
Lombiq/UI-Testing-Toolbox pull request #354
Opened 2024-04-08 13:52 UTC by AydinE

[OSOE-770](https://lombiq.atlassian.net/browse/OSOE-770)
Added ability to get parsed html-validate output
Fixes #337

[OSOE-770]: https://lombiq.atlassian.net/browse/OSOE-770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-08 13:53 UTC, AydinE commented on Lombiq.Tests.UI/Models/HtmlValidationError.cs
> +    public JsonElement Context { get; set; }
The reason this is JsonElement instead of something else is because this doesn't seem to have the same properties every time see sample output below:
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/1669059/631a23f4-bc66-46c1-b7a8-d0bfd40de41c)

2024-04-11 01:33 UTC, DemeSzabolcs requested changes

2024-04-11 01:33 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Extensions/HtmlValidationResultExtensions.cs
> +    public static async Task<IEnumerable<HtmlValidationError>> GetParsedErrorsAsync(this HtmlValidationResult result)
It might be a good idea to rename it to something more specific like `GetJsonParsedErrorsAsync`, if we would add more formatters.

2024-04-11 01:33 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Models/HtmlValidationError.cs
> +public class HtmlValidationError
I think this should be more specific too (like `JsonHtmlValidationError` or something like that.

2024-04-11 01:33 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Services/HtmlValidationConfiguration.cs
> +        ResultFileFormatter = HtmlValidateFormatter.Names.Json,
Add a note about the formatter in: https://github.com/Lombiq/UI-Testing-Toolbox/blob/dev/Lombiq.Tests.UI/Docs/Configuration.md and a note on how to use the original one instead (if someone wants to).

2024-04-11 01:33 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Services/HtmlValidationConfiguration.cs
It's good that now we can filter in a simpler way, but the output message should be adjusted too, because now it's not human readable: 

```
    Lombiq.Tests.UI.Exceptions.PageChangeAssertionException : An assertion during the page change event has failed on page https://localhost:9024/ (Lombiq's OSOCE - UI Testing - Blog).
    ---- Lombiq.Tests.UI.Exceptions.HtmlValidationAssertionException : await validationResult.GetParsedErrorsAsync()
        should be empty but had
    1
        item and was
    [Lombiq.Tests.UI.Models.HtmlValidationError (2681320)] Check the HTML validation report in the failure dump for details.
    -------- Shouldly.ShouldAssertException : await validationResult.GetParsedErrorsAsync()
        should be empty but had
    1
        item and was
    [Lombiq.Tests.UI.Models.HtmlValidationError (2681320)]
```

![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/80963259/b9c48736-45ee-4dbe-bd2c-a29a116be517)

Previously the errors names were listed here.
Like this:
```
  Lombiq.Tests.UI.Exceptions.PageChangeAssertionException : An assertion during the page change event has failed on page https://localhost:9022/ (Lombiq's OSOCE - UI Testing - Blog).
  ---- Lombiq.Tests.UI.Exceptions.HtmlValidationAssertionException : validationResult.Output
      should be empty but was
  "G:\Work\Open-Source-Orchard-Core-Extensions\test\Lombiq.OSOCE.Tests.UI\bin\Debug\net8.0\HtmlValidationTemp\5bc0f7c6-8eb3-4ec7-acf5-6744e3373ea6.html
    44:8  error  Prefer to use the native <button> element  prefer-native-element
  
  ✖ 1 problem (1 error, 0 warnings)
  
  More information:
    https://html-validate.org/rules/prefer-native-element.html
  " Check the HTML validation report in the failure dump for details.
  -------- Shouldly.ShouldAssertException : validationResult.Output
      should be empty but was
  "G:\Work\Open-Source-Orchard-Core-Extensions\test\Lombiq.OSOCE.Tests.UI\bin\Debug\net8.0\HtmlValidationTemp\5bc0f7c6-8eb3-4ec7-acf5-6744e3373ea6.html
    44:8  error  Prefer to use the native <button> element  prefer-native-element
  
  ✖ 1 problem (1 error, 0 warnings)
  
  More information:
    https://html-validate.org/rules/prefer-native-element.html
  "
```
(To repro this, just remove the custom `configuration.HtmlValidationConfiguration.AssertHtmlValidationResultAsync` from a test that uses it. Also to get what should the output look like, you can check out the `dev` branch and do the same thing.)

And I think the same thing applies to the `HtmlValidationReport.txt` (that is generated in the UI test failure dump (locally `\Open-Source-Orchard-Core-Extensions\test\Lombiq.OSOCE.Tests.UI\bin\Debug\net8.0\FailureDumps`). I think the format of that changed too:

Previously:
[HTMLVA~1.TXT](https://github.com/Lombiq/UI-Testing-Toolbox/files/14940033/HTMLVA.1.TXT)

Now:
[HtmlValidationReport.txt](https://github.com/Lombiq/UI-Testing-Toolbox/files/14940038/HtmlValidationReport.txt)

2024-04-18 13:19 UTC, AydinE commented on Lombiq.Tests.UI/Services/HtmlValidationConfiguration.cs
@DemeSzabolcs I have set the output back to the text for the output file so that should be fixed. For the message on the actual test run I can not fully put that back the way it was because it's just the way that Shouldly reports on the errors based on the new format.

What I did try was pass a custom message to shouldly and then the test output will look like: [here](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/pull/738/commits/86c82562203f0a3d4f948138e9245dd1120d80a5#diff-2af6fb34d863dcd5368561a878f904cf43ec23c5e9f70feb218a89f36bee2845R32)
![image](https://github.com/Lombiq/UI-Testing-Toolbox/assets/1669059/6aeabda6-966e-4312-91b0-cd883551e4fa)

But this would mean that we'd have to pass in the custom string formatter into everywhere we use shouldly. If you have another idea on how to solve this I'd be happy to hear.

2024-04-20 19:27 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Services/HtmlValidationConfiguration.cs
Well if it's this way because of how Shouldly summarizes the error and it's not our code, then I think using that custom message is a fine solution.

2024-05-03 17:53 UTC, closed without merging