Generalize Failure Dump to Test Dump
Lombiq/UI-Testing-Toolbox pull request #406
Opened 2024-09-05 20:29 UTC by Piedone

2024-09-13 23:02 UTC, sarahelsaig requested changes

2024-09-13 23:02 UTC, sarahelsaig commented on Lombiq.Tests.UI/Exceptions/TestDumpItemAlreadyExistsException.cs
> +            $"A Test dump item with the same file name already exists. File name: {fileName}."
I guess the capitalization here was accidental?
```suggestion
            $"A test dump item with the same file name already exists. File name: {fileName}."
```

2024-09-13 23:02 UTC, sarahelsaig commented on Lombiq.Tests.UI/Models/TestDumpItemGeneric.cs
> +            throw new ArgumentException($"{nameof(content)} is not a Stream and {nameof(getStream)} can't be null.");
It would be better to phrase the exception message as an instruction than a status report. Easier to understand during debugging,

```suggestion
            throw new ArgumentException(
                $"{nameof(content)} must be of type {nameof(Stream)} or {nameof(getStream)} must not be null.");
```

2024-09-13 23:02 UTC, sarahelsaig commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +                        "on why it's failing in the TestDumps folder: {1}",
It's not necessary to re-state the folder name, it's already in the `dumpFolderAbsolutePath`.
```suggestion
                        "on why it's failing in the test dump folder: {1}",
```

2024-09-13 23:02 UTC, sarahelsaig commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +        CaptureMarkupValidationResults(ex, debugInformationPath);
Each line in this method is separated with a blank line, which doesn't seem readable.
Can we group the `Capture*()` method calls together?
```suggestion
        if (_context.IsBrowserRunning) await CaptureBrowserUsingDumpsAsync(debugInformationPath);
        if (_dumpConfiguration.CaptureAppSnapshot) await CaptureAppSnapshotAsync(dumpContainerPath);
        CaptureMarkupValidationResults(ex, debugInformationPath);
```

2024-09-13 23:02 UTC, sarahelsaig commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +            ((testDumpContainer == null || !testDumpContainer.Any()) && additionalDumpProcess == null))
imo it's easier to understand with less parentheses
```suggestion
        if (!_dumpConfiguration.CreateTestDump ||
            (testDumpContainer?.Any() != true && additionalDumpProcess == null))
```

2024-09-15 14:45 UTC, Piedone commented on Lombiq.Tests.UI/Exceptions/TestDumpItemAlreadyExistsException.cs
> +            $"A Test dump item with the same file name already exists. File name: {fileName}."
Yep!

2024-09-15 14:49 UTC, Piedone commented on Lombiq.Tests.UI/Models/TestDumpItemGeneric.cs
> +            throw new ArgumentException($"{nameof(content)} is not a Stream and {nameof(getStream)} can't be null.");
Yep.

2024-09-15 14:49 UTC, Piedone commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +                        "on why it's failing in the TestDumps folder: {1}",
Indeed.

2024-09-15 14:49 UTC, Piedone commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +        CaptureMarkupValidationResults(ex, debugInformationPath);
Yeah, better like that.

2024-09-15 17:21 UTC, merged