Adding the ability to maintain more than one Cloudflare IP Access Rule for remote tests
Lombiq/UI-Testing-Toolbox pull request #431
Opened 2024-12-19 15:44 UTC by Piedone

2024-12-27 14:28 UTC, DemeSzabolcs requested changes

2024-12-27 14:28 UTC, DemeSzabolcs commented on Lombiq.Tests.UI/Helpers/CloudflareHelper.cs
>                      oldIpAccessRuleId);
Is there a point in using `oldIpAccessRuleId` in one place but `value` in another? Since here `oldIpAccessRuleId` is made equal to `value`.

2024-12-27 18:17 UTC, Piedone commented on Lombiq.Tests.UI/Helpers/CloudflareHelper.cs
>                      oldIpAccessRuleId);
Not really, this is just a leftover. Fixed it.

2024-12-29 02:35 UTC, DemeSzabolcs approved these changes

2024-12-29 02:36 UTC, merged