Upgrade to xUnit 3 and handling test cancellations gracefully
Lombiq/UI-Testing-Toolbox pull request #432
Opened 2024-12-22 01:16 UTC by Piedone

2025-01-16 21:49 UTC, dministro requested changes

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI.Samples/Tests/RemoteTests.cs
> +// - In local tests, you have a much lower-level access to the app: E.g., you can access the Orchard Core log, use
Did you mean "higher-level"?

```suggestion
// - In local tests, you have much higher-level access to the app: E.g., you can access the Orchard Core log, use
```

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/BasicOrchardFeaturesTesting/WorkflowsFeatureTestingUITestContextExtensions.cs
> +                context.WaitElementToNotChange(By.ClassName("jtk-connector")); // #spell-check-ignore-line
Why this change is necessary?

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/Models/UITestManifest.cs
> +    public string Name => XunitTest?.TestDisplayName;
Can `TestContext.Current.Test` `null` here?

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/Models/UITestManifest.cs
>      public Func<UITestContext, Task> TestAsync { get; set; }
This can be a constructor parameter.
![image](https://github.com/user-attachments/assets/6ecf2d99-ec7a-48bd-b498-c8677ba946cb)

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/OrchardCoreUITestBase.cs
> +        var testManifest = new UITestManifest { TestAsync = testAsync };
See my comment for `UITestManifest.TestAsync`.

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/RemoteUITestBase.cs
> +        var testManifest = new UITestManifest { TestAsync = BaseUriVisitingTest };
See my comment for `UITestManifest.TestAsync`.

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +        _configuration.TestCancellationToken.Register(() =>
I'm not sure, but I think `System.Threading.CancellationTokenRegistration` returned by `CancellationToken.Register` needs to be disposed.

Testing `_configuration.TestCancellationToken.IsCancellationRequested` also wellcome before starting the whole ceremony.

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +            await testTask;
In case when a cancellation is requested on the `_configuration.TestCancellationToken`, the `timeoutTask.IsCompleted` will be `true`.

2025-01-16 21:49 UTC, dministro commented on Lombiq.Tests.UI/Services/UITestExecutor.cs
>          {
The `_configuration.TestCancellationToken.IsCancellationRequested` can also stop the loop.

2025-01-20 00:27 UTC, Piedone commented on Lombiq.Tests.UI.Samples/Tests/RemoteTests.cs
> +// - In local tests, you have a much lower-level access to the app: E.g., you can access the Orchard Core log, use
I did mean lower level: the app runs in the same process, so you can communicate with its container and types directly, whereas in prod, all you have is the public UI.

2025-01-20 00:28 UTC, Piedone commented on Lombiq.Tests.UI/BasicOrchardFeaturesTesting/WorkflowsFeatureTestingUITestContextExtensions.cs
> +                context.WaitElementToNotChange(By.ClassName("jtk-connector")); // #spell-check-ignore-line
This waits for the connector to settle after the drag and drop. The test was flaky without this, since the connection might not be registered and thus saved before it.

2025-01-20 00:29 UTC, Piedone commented on Lombiq.Tests.UI/Models/UITestManifest.cs
> +    public string Name => XunitTest?.TestDisplayName;
Not, actually.

2025-01-20 00:40 UTC, Piedone commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +        _configuration.TestCancellationToken.Register(() =>
It indeed needs to be disposed, so I added that.

I don't really understand the rest of your comment: xUnit 3 supports cancellations. If we want the tests to clean up after themselves when such a cancellation happens, hooking into it is necessary. Running `ShutdownAsync()` will do the clean-up. Thus after this, a cancelled test won't leave ChromeDriver processes or browser windows open.

2025-01-23 04:14 UTC, Piedone commented on Lombiq.Tests.UI.Samples/Tests/InteractiveModeTests.cs
> -            });
I've spent half a day trying to make this reliable, i.e. not hang randomly (that hung the tests too), and be reliable with its interactions. I couldn't get there, it was always flaky. I don't see any point in trying harder, we don't really need this test.

2025-02-11 21:39 UTC, dministro requested changes

2025-02-11 21:39 UTC, dministro commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +            await testTask;
I think we dont need to `await` twice
```suggestion
            }

            // Since the timeout task is not yet completed but the Task.WhenAny has finished, the test task is done in
            // some way. So it's safe to await it here. It's also necessary to cleanly propagate any exceptions that may
            // have been thrown inside it.
            await testTask;
```

2025-02-12 00:05 UTC, Piedone commented on Lombiq.Tests.UI/Services/UITestExecutionSession.cs
> +            await testTask;
Indeed.

2025-02-13 21:58 UTC, dministro approved these changes

2025-02-13 22:11 UTC, merged