Basic Orchard feature tests
Lombiq/UI-Testing-Toolbox pull request #99
Opened 2021-10-06 10:34 UTC by YevgeniyShunevych

2021-10-06 18:37 UTC, Piedone requested changes

2021-10-06 18:37 UTC, Piedone commented on Lombiq.Tests.UI/Pages/OrchardCoreSetupParameters.cs
> +        public string Password { get; set; } = DefaultUser.Password;
Good point. While we're at it, we could have a const for the Email in `DefaultUser` too.

2021-10-06 18:37 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +                AtataContext.Current.Driver.Perform(x => x.SendKeys(element, text));
Use a descriptive variable name instead of `x`.

2021-10-06 18:37 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +        public override void Execute<TOwner>(IUIComponent<TOwner> component, string value)
DRY this logic with the one in `FormUITestContextExtensions`.

2021-10-07 07:46 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Pages/OrchardCoreSetupParameters.cs
> +        public string Password { get; set; } = DefaultUser.Password;
Added `Email` property.

2021-10-07 07:49 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +        public override void Execute<TOwner>(IUIComponent<TOwner> component, string value)
There is a problem here. In `SetsValueReliablyAttribute` I don't have an instance of `UITestContext` in order to invoke its extension method.

2021-10-07 08:58 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +                AtataContext.Current.Driver.Perform(x => x.SendKeys(element, text));
Renamed.

2021-10-07 13:28 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +        public override void Execute<TOwner>(IUIComponent<TOwner> component, string value)
You can just put the logic here into a third method that accepts the driver, and then use that from both places: Here it would get the driver from `AtataContext.Current`, otherwise from `UITestContext`.

2021-10-07 14:29 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +        public override void Execute<TOwner>(IUIComponent<TOwner> component, string value)
OK. I was also thinking about that. Will do it.

2021-10-07 15:08 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +        public override void Execute<TOwner>(IUIComponent<TOwner> component, string value)
Refactored.

2021-10-12 18:31 UTC, Piedone requested changes

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                RecipeId = "Lombiq.OSOCE.BasicOrchardFeaturesTests",
This can't really be a default as it's very specific to the OSOCE solution. It needs to be supplied from the sample code.

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldNotBe(userName);
```suggestion
                    context.GetCurrentUserName().ShouldBeEmpty();
```

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Models/UserRegistrationModel.cs
> +    public class UserRegistrationModel
```suggestion
    public class UserRegistrationParameters
```

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicWebDriverExtensions.cs
> +    public static class BasicWebDriverExtensions
```suggestion
    public static class FormWebDriverExtensions
```

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GoToRegistrationPage()
Let's click the previously checked link instead of going to the registration page directly.

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    .ValidationMessages[x => x.Email].Should.BeVisible());
Use a descriptive variable name instead of `x`.

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +            =>
```suggestion
        public static UITestContext TestTurningFeatureOnAndOff(this UITestContext context, string featureName = "Background Tasks") =>
```

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    .AggregateAssert(x => x
Use a descriptive variable name instead of `x`, also below.

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Pages/OrchardCoreAdminPage.cs
> +            AlertMessages.Should.Contain(x => x.IsSuccess && expectedMatch.IsMatch(x.Text.Value, expectedText));
Use a descriptive variable name instead of `x`.

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldBe(model.UserName);
After this, it would be useful to log out. I'm not actually sure why `TestRegistrationWithAlreadyRegisteredEmail()` works after this but perhaps it's just an oversight that as a logged in user you can fill out the registration page.

2021-10-12 18:31 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    .ShouldLeaveSetupPage());
Similarly in the other cases too:

```suggestion
                () => context
                    .GoToSetupPage()
                    .SetupOrchardCore(parameters)
                    .ShouldLeaveSetupPage());
```

2021-10-14 08:50 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldNotBe(userName);
Currently, how I see Orchard works. Being already logged in, user can go to login page and try to login. If login failed, the user remains still be logged in with previously login data. Current implementation covers this scenario.

So if we change assertion to `ShouldBeEmpty()` and invoke `TestLoginWithInvalidData` when user is logged in, we'll get an assertion exception `"should be empty but was "TestUser""`. So I see few solutions here:
1. Remain current implementation.
1. Use `ShouldBeEmpty()`.
1. Use `ShouldBeEmpty()`, but add logout step to the test beginning.

@Piedone, which one to choose?

2021-10-14 11:49 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GoToRegistrationPage()
Updated.

2021-10-14 11:49 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldBe(model.UserName);
Updated the test.

2021-10-14 11:59 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                RecipeId = "Lombiq.OSOCE.BasicOrchardFeaturesTests",
OK. So first of all I will then use `new OrchardCoreSetupParameters()` by default in `TestSetup` method. 

What if we add optional `OrchardCoreSetupParameters` parameter to `TestBasicOrchardFeatures`? Then I can update the test method this way:

```cs
[Theory, Chrome]
public Task BasicOrchardFeaturesShouldWork(Browser browser) =>
    ExecuteTestAsync(
        context => context.TestBasicOrchardFeatures(
            new OrchardCoreSetupParameters
            {
                RecipeId = "Lombiq.OSOCE.BasicOrchardFeaturesTests",
            }),
        browser);
```

2021-10-14 14:39 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldNotBe(userName);
A safety login step before with `SignOutDirectly()` is good.

2021-10-14 14:40 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                RecipeId = "Lombiq.OSOCE.BasicOrchardFeaturesTests",
Looks good!

2021-10-15 12:12 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                RecipeId = "Lombiq.OSOCE.BasicOrchardFeaturesTests",
Done,

2021-10-15 12:28 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldNotBe(userName);
Do you mean "A safety **logout** step"? Or something else?

2021-10-15 15:47 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldNotBe(userName);
Yes, sorry.

2021-10-15 16:24 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +                    context.GetCurrentUserName().ShouldNotBe(userName);
No problem. Updated the test.

2021-10-17 18:25 UTC, Piedone requested changes

2021-10-17 18:25 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
>              =>
There are a couple of other such examples in this class too.

```suggestion
        public static UITestContext TestContentOperations(this UITestContext context, string pageTitle = "Test page") =>
```

2021-10-17 18:25 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
There are a couple of such `AtataContext.Current` references. We've consciously avoided this until now due to the references possibly being lost when `async` code is in the tests, especially if multiple ones are executed in parallel. Hence `UITestContext.Scope.AtataContext` too. Please use `UITestContext` instead too.

2021-10-17 18:38 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        public static UITestContext TestBasicOrchardFeatures(this UITestContext context, OrchardCoreSetupParameters setupParameters = null) =>
Add some docs on the public methods, please, especially outlining any assumptions they make, like the site not being set up.

2021-10-18 06:13 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
>              =>
Updated.

2021-10-18 07:52 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
I thought that `AtataContext.Current` should not be such issue as before, as there was improvement on that. Anyway, `AtataContext.Current` is used in Atata itself in some places.

I would like to use `UITestContext` here but I can't get a reference to current instance in behavior attribute.

Either way, I have a suggestion. I can make [Driver property of UIComponent](https://github.com/atata-framework/atata/blob/bf4cbd0dd2974c2b5112f3ee6107e129d154bccb/src/Atata/Components/UIComponent.cs#L31) public and add it to `IUIComponent<TOwner>`. Then instead of using `AtataContext.Current.Driver` we'll be able to use `component.Driver`. I'll just need a couple of days to release Atata v1.13.0 with this change, as there are few other things that I want to add to upcoming Atata version release.

2021-10-18 12:00 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
Even after the improvements we had issues, hence the `GoToPage<T>()` extension to avoid using `AtataContext.Current`.

While using `component.Driver` would work here, we also have `AtataContext.Current.BaseUrl` references. Why not just add a `UITestContext` property onto the page classes that you can then access?

2021-10-20 10:53 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
I thought and reviewed Atata a bit. I am thinking to add `public AtataContext Context { get; }` property to `UIComponent`. This way we'll have and be able to use `AtataContext` instance in page objects, in attributes, etc.

2021-10-20 13:26 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        public static UITestContext TestBasicOrchardFeatures(this UITestContext context, OrchardCoreSetupParameters setupParameters = null) =>
I've added XML comments. Please check it out.

2021-10-20 21:35 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
Would that mean that after `UITestContext.Scope.AtataContext.Go.To<MyPage>()` you'd be able to access the same `UITestContext.Scope.AtataContext` (and not `AtataContext.Current`) from inside `MyPage`? If yes then great!

2021-10-20 21:46 UTC, Piedone requested changes

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// with <c>"SaaS"</c> <see cref="OrchardCoreSetupParameters.RecipeId"/> value.
If you want multiple paragraphs here (it seems to me based on the line breaks) then add multiple `<para>` tags, please. Otherwise, break comments at 120 characters (i.e. the first soft limit also added by the Analyzers). This extension can do this automatically: https://marketplace.visualstudio.com/items?itemName=stkb.rewrap

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// The test method assumes that site is not set up.
Also below:

```suggestion
        /// The test method assumes that the site is not set up.
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// <param name="context">The context.</param>
No need to add a comment for the `this` parameter as you never have to explicitly provide it.

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// Tests negatively the site setup with optionally set <paramref name="parameters"/>.
```suggestion
        /// Tests the site setup negatively with optionally set <paramref name="parameters"/>.
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// The test method assumes that "Users Registration" Orchard feature is enabled
```suggestion
        /// The test method assumes that the "Users Registration" Orchard feature is enabled
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// and there is no registered user with the given <see cref="UserRegistrationParameters.Email"/> value.
Should be email or username values, or isn't this how it works?

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// Tests negatively the user registration with optionally specified invalid <paramref name="parameters"/>.
```suggestion
        /// Tests the user registration negatively with optionally specified invalid <paramref name="parameters"/>.
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// The test method assumes that "Users Registration" Orchard feature is enabled.
```suggestion
        /// The test method assumes that the "Users Registration" Orchard feature is enabled.
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// Tests negatively the user registration with optionally specified <paramref name="parameters"/>
```suggestion
        /// Tests the user registration negatively with optionally specified <paramref name="parameters"/>
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// The test method assumes that "Users Registration" Orchard feature is enabled
```suggestion
        /// The test method assumes that the "Users Registration" Orchard feature is enabled
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// and there is already registered user with the given <see cref="UserRegistrationParameters.Email"/> value.
```suggestion
        /// and there is an already registered user with the given <see cref="UserRegistrationParameters.Email"/> value.
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// <item><description>Navigate to "Content / Content Items" page.</description></item>
```suggestion
        /// <item><description>Navigate to the "Content / Content Items" page.</description></item>
```

2021-10-20 21:46 UTC, Piedone commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// <item><description>Navigate to "Configuration / Features" page.</description></item>
```suggestion
        /// <item><description>Navigate to the "Configuration / Features" page.</description></item>
```

2021-10-21 06:20 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// with <c>"SaaS"</c> <see cref="OrchardCoreSetupParameters.RecipeId"/> value.
OK, reformatted.

2021-10-21 06:31 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// <param name="context">The context.</param>
OK, removed. I just get used to have a StyleCop warning in Atata for missing parameter comment.

2021-10-21 07:07 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Extensions/BasicOrchardFeaturesTestingUITestContextExtensions.cs
> +        /// and there is no registered user with the given <see cref="UserRegistrationParameters.Email"/> value.
You are right. I've updated the comment.

2021-10-21 13:38 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
Basically, yes.

2021-10-21 13:53 UTC, Piedone commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
Sounds good then.

2021-10-21 15:49 UTC, YevgeniyShunevych commented on Lombiq.Tests.UI/Attributes/Behaviors/SetsValueReliablyAttribute.cs
> +            var driver = AtataContext.Current.Driver;
I've released Atata v1.13.0 and updated `AtataContext` related code here.

2021-10-21 16:57 UTC, merged